# Generated by Django 3.2.15 on 2022-10-20 07:30

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
