# Generated by Django 3.2.16 on 2022-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
